# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=25)),
                ('unit', models.CharField(max_length=25)),
                ('calories_burned', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=25)),
                ('unit', models.CharField(max_length=25)),
                ('calories', models.CharField(max_length=25)),
                ('carbs', models.CharField(max_length=25)),
                ('proteins', models.CharField(max_length=25)),
                ('lipids', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='share_health.Exercise')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='share_health.Nutrition')),
            ],
        ),
    ]
